name: arachne
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # data
  - polars>=0.20
  - pandas>=2.0
  - pyarrow>=14

  # neo4j client
  - neo4j>=5.20

  # deashboarding
  - streamlit>=1.33
  - plotly>=5.20

  # utils
  - pyyaml>=6.0
  - pydantic>=2.6
  - rich>=13.7
  - python-dotenv>=1.0

  # dev/test
  - pytest>=8.0
  - ruff>=0.4

  # graph visualization
  - pip:
      - pyvis>=0.3.2